### ISSUE TITLE
使用 v1.1.6 二进制文件部署遇到错误

### ISSUE THREAD

**Issue by mfuuzy** [dotbitHQ/das-account-indexer#4]
1、你们似乎没有把最新的版本上传到  hub.docker.com上面
2、下载二进制文件部署，遇到如下错误
```
2022-07-15 15:54:37.38734819	INFO	cmd/main.go:67	▶ [main] db ok

2022-07-15 15:54:37.38790774	INFO	cmd/main.go:80	▶ [main] ckb node ok

panic: runtime error: slice bounds out of range [:4] with capacity 0

goroutine 1 [running]:
github.com/dotbitHQ/das-lib/witness.ConfigCellDataBuilderRefByTypeArgs(0xc00018a000, 0xc0005180c0, 0xe34d96, 0xa, 0x0, 0x0)
	/mnt/server/go/gopath/pkg/mod/github.com/dotbit!h!q/das-lib@v0.0.0-20220704023511-4dd5e3047598/witness/config_cell.go:137 +0x2b05
github.com/dotbitHQ/das-lib/witness.ConfigCellDataBuilderByTypeArgs(0xc0005180c0, 0xe34d96, 0xa, 0x0, 0x0, 0x0)
	/mnt/server/go/gopath/pkg/mod/github.com/dotbit!h!q/das-lib@v0.0.0-20220704023511-4dd5e3047598/witness/config_cell.go:219 +0x65
github.com/dotbitHQ/das-lib/core.(*DasCore).ConfigCellDataBuilderByTypeArgs(0xc00009a000, 0xe34d96, 0xa, 0xd217c0, 0xc00044b080, 0x0)
	/mnt/server/go/gopath/pkg/mod/github.com/dotbit!h!q/das-lib@v0.0.0-20220704023511-4dd5e3047598/core/config_cell.go:157 +0x1a7
github.com/dotbitHQ/das-lib/core.(*DasCore).InitDasConfigCell(0xc00009a000, 0xc0004de720, 0x1634c50)
	/mnt/server/go/gopath/pkg/mod/github.com/dotbit!h!q/das-lib@v0.0.0-20220704023511-4dd5e3047598/core/config_cell.go:65 +0xf0c
main.runServer(0xc00042eec0, 0x0, 0x2)
	/mnt/server/das-account-indexer/das-account-indexer/cmd/main.go:95 +0x57f
github.com/urfave/cli/v2.(*App).RunContext(0xc000126b60, 0xf70790, 0xc00011c000, 0xc00013c000, 0x2, 0x2, 0x0, 0x0)
	/mnt/server/go/gopath/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
	/mnt/server/go/gopath/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/mnt/server/das-account-indexer/das-account-indexer/cmd/main.go:43 +0x1e5
```

**Comment by mfuuzy** [comment]
换了个四核的服务器，跑起来了
