### ISSUE TITLE
连接ckb testnet同步运行报错

### ISSUE THREAD

**Issue by mfuuzy** [dotbitHQ/das-account-indexer#8]
das版本：v1.3.1
ckb 版本: testnet v0.108.0

错误信息如下：
```
2023-03-20 09:07:01.927908917   INFO    block_parser/block_parser.go:205        ▶ [block_parser] parserConcurrencyMode: 8500397 500

2023-03-20 09:07:01.933013286   INFO    block_parser/block_parser.go:213        ▶ [block_parser] parserConcurrencyMode: 8500397 0x4b9da7acacdfcbb5a5328819ffe9dffe9ae6a3e2d4a654a56f0e0590d372d7e7 0xfee0813aed813541be72d693b73a4de3405a4403821b11bc50cf601f5ce78eda

2023-03-20 09:07:01.93716231    INFO    block_parser/block_parser.go:116        ▶ [block_parser] parsingBlockData txHash: 0x9b7bc45781c021c7e055215b7b04a97ee72b595ebbcd563ac39bd47dfb4c61a5

2023-03-20 09:07:01.937209668   WARN    block_parser/block_parser.go:119        ▶ [block_parser] ActionDataBuilderFromTx err: not exist action data

2023-03-20 09:07:01.937219837   INFO    block_parser/block_parser.go:116        ▶ [block_parser] parsingBlockData txHash: 0x154312a99a8e45061c872cf697724afd0ab819cbd79ac12697bed029d0a0abf8

2023-03-20 09:07:01.937237915   INFO    block_parser/block_parser.go:131        ▶ [block_parser] other handle: 0x154312a99a8e45061c872cf697724afd0ab819cbd79ac12697bed029d0a0abf8 pre_register

2023-03-20 09:07:01.937250588   INFO    block_parser/block_parser.go:116        ▶ [block_parser] parsingBlockData txHash: 0x13bcd32840f527aa9b33580eabc92ee3e6b28f63c126288be8a1d8e3210fce98

2023-03-20 09:07:01.937267441   INFO    block_parser/block_parser.go:131        ▶ [block_parser] other handle: 0x13bcd32840f527aa9b33580eabc92ee3e6b28f63c126288be8a1d8e3210fce98 propose

2023-03-20 09:07:01.937276972   INFO    block_parser/block_parser.go:116        ▶ [block_parser] parsingBlockData txHash: 0x5c3fb75b4624b77f65eec7798d5aaec07f441f61298cc8deaa81e44750d71022

2023-03-20 09:07:01.937304887   INFO    block_parser/action_propose_cell.go:18  ▶ [block_parser] das tx: confirm_proposal 0x5c3fb75b4624b77f65eec7798d5aaec07f441f61298cc8deaa81e44750d71022

panic: runtime error: index out of range [0] with length 0
goroutine 69 [running]:
github.com/dotbitHQ/das-lib/core.(*DasAddressFormat).halfArgsToHex(0xc000618340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /mnt/server/go/gopath/pkg/mod/github.com/dotbit!h!q/das-lib@v1.0.1-0.20221229085506-50b5a890b633/core/address.go:275 +0x77b
github.com/dotbitHQ/das-lib/core.(*DasAddressFormat).ArgsToHex(0xc000618340, 0xc0004dc0f0, 0x2a, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /mnt/server/go/gopath/pkg/mod/github.com/dotbit!h!q/das-lib@v1.0.1-0.20221229085506-50b5a890b633/core/address.go:244 +0x1cb
das-account-indexer/block_parser.(*BlockParser).ActionConfirmProposal(0xc00007ef00, 0xc00017c4c0, 0x8a7901, 0xc0005aab50)
        /mnt/server/das-account-indexer/das-account-indexer/block_parser/action_propose_cell.go:35 +0x63d
das-account-indexer/block_parser.(*BlockParser).parsingBlockData(0xc00007ef00, 0xc000616fa0, 0x4, 0x4)
        /mnt/server/das-account-indexer/das-account-indexer/block_parser/block_parser.go:134 +0x3cf
das-account-indexer/block_parser.(*BlockParser).parserConcurrencyMode(0xc00007ef00, 0x438b697b, 0x1668c80)
        /mnt/server/das-account-indexer/das-account-indexer/block_parser/block_parser.go:215 +0x355
das-account-indexer/block_parser.(*BlockParser).RunParser.func1(0xc00007ef00)
        /mnt/server/das-account-indexer/das-account-indexer/block_parser/block_parser.go:78 +0x445
created by das-account-indexer/block_parser.(*BlockParser).RunParser
        /mnt/server/das-account-indexer/das-account-indexer/block_parser/block_parser.go:65 +0x12b
```

**Comment by scorpiotzh** [comment]
The testnet is developing new features recently. You can compile the dev branch of the repository to solve the problem. The version will be updated in two days.
